// This file is automatically generated and should not be edited.
// Your Firebase app configuration object.
// IMPORTANT: Replace the placeholder values below with your actual
// Firebase project configuration from the Firebase console.
// Go to your Project Settings > General tab > Your apps card > Web app.
// https://console.firebase.google.com/
export const firebaseConfig = {
  apiKey: "AIzaSyDVSOAXGKoUFJx9T0jp2MFdo31FPj0n0vo",
  authDomain: "smart-social-scheduler.firebaseapp.com",
  projectId: "smart-social-scheduler",
  storageBucket: "smart-social-scheduler.appspot.com",
  messagingSenderId: "207340154187",
  appId: "1:207340154187:web:65ec195793ac89766a8cce",
  measurementId: "G-SSRCZ9F2YT"
};
